# Generated by Django 4.0.1 on 2022-01-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_image',
            new_name='contact_picture',
        ),
    ]
