# Generated by Django 4.0.1 on 2024-09-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_prefix_user_suffix'),
        ('contacts', '0005_alter_contact_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contacts.contact')),
                ('company_name', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture', models.FilePathField(verbose_name='/home/bikodes/dev/viagem/chapiana-api')),
                ('description', models.TextField(max_length=100, null=True)),
                ('file', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relation', models.CharField(choices=[('Assistant', 'Assistant'), ('Brother', 'Brother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Friend', 'Friend'), ('Manager', 'Manager'), ('Partner', 'Partner'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Relative', 'Relative')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sur_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='MobileInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('W', 'Work'), ('H', 'Home')], default='W', max_length=10)),
                ('address', models.TextField(max_length=150, null=True)),
                ('address_type', models.CharField(choices=[('W', 'Work'), ('H', 'Home')], default='W', max_length=10)),
                ('contanct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='DateInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
    ]
